services:
  - type: web
    plan: free
    name: Filestorebot
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/shanclient/filestore.git     
    branch: main
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: CHANNEL_ID 
        sync: false
      - key: OWNER_ID
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URL
        sync: false 
      - key: START_MESSAGE
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false    
      - key: FORCE_SUB_MESSAGE
        sync: false    
      - key: PROTECT_CONTENT
        sync: false    
    autoDeploy: false 
